# Generated by Django 5.0.6 on 2024-07-03 19:08

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_publicationspage_publicationyear_publication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissionpage',
            old_name='content',
            new_name='intro_text',
        ),
        migrations.AddField(
            model_name='admissionpage',
            name='allotment_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionpage',
            name='allotment_notice',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='admissionpage',
            name='intro_heading',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=250)),
                ('link', models.URLField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='main.admissionpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
