# Generated by Django 5.0.6 on 2024-07-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_homepageannouncement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
