# Generated by Django 5.0.6 on 2024-07-05 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_contactus'),
        ('wagtailmedia', '0004_duration_optional_floatfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media'),
        ),
    ]
