# Generated by Django 5.0.7 on 2024-07-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_facility_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facility',
        ),
    ]
